---
title: "Semester project for ECON4170"
format: html
editor: visual
execute: 
  echo: false
  warning: false
  message: false
---

## introduction

this is a semester project where we will be making a model to see if we can predict the price of electricity in Norway, one day (24 hours) ahead of time. we want to create a model that beats the naive benchmark.

## Data

the data that we will be using comes from ENTSO-E. we have gotten a yearly report for this year (up to the 27th of October) with the time between measurements being every 15 minutes, across an entire 24-hour period. its an excel file (CSV). the original currency that is displayed in the excel file is in EUR.

we will transform this data to fit our needs as we go. to start, we will be adding a new collumn that converts the currency and price, to something that displays NOK. To do this, we will use todays current exchange rate. (11,68 NOK per EUR, as of the 26th of October 2025)

## Running Code

```{r}

##first dataset: electricity price history

library(tidyverse) #standard package for most projects in this course
library(janitor) #used by professor in seminar 5 solution
library(lubridate) #found in syllabus

ELP <- readr::read_csv("GUI_ENERGY_PRICES_202412312300-202512312300.csv") %>%
  clean_names() %>%
  mutate(
    Price_time = dmy_hms(sub("-.*","",mtu_cet_cest)),
    hourly_price = floor_date(Price_time, "hour"),
    Price_EUR = day_ahead_price_eur_m_wh,
    Price_NOK = Price_EUR * 11.68) %>%
  group_by(hourly_price) %>%
  summarise(
    Price_EUR = mean(Price_EUR, na.rm = TRUE),
    Price_NOK = mean(Price_NOK, na.rm = TRUE), 
    .groups = "drop")


head(ELP) 

## other vaiables: water reservior levels and temprature history

water_level <- readr::read_csv("GUI_WATER_RESERVOIRS_HYDRO_STORAGE_202412312300-202512312300") 

head(water_level)


```
